global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  # repeat_interval: 10s
  receiver: "live_monitoring"

receivers:
  - name: "live_monitoring"
    email_configs:
      - to: "helloworld@gmail.com"
        from: "helloworld@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "helloworld@gmail.com"
        auth_identity: "helloworld@gmail.com"
        auth_password: "your_app_password"
        require_tls: true
        send_resolved: true
