global:
  scrape_interval: 15s
  external_labels:
    monitor: "demo_monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "my-service"
    scrape_interval: 5s
    static_configs:
      - targets: ["web:4000"]
        labels:
          service: "my-service"
          group: "development"
  # - job_name: 'node-exporter'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  # - job_name: 'cadvisor'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

rule_files:
  - "alert_rules.yaml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
