apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: true
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with external link.
        - datasourceUid: tempo
          matcherRegex: 'traceId (\w+)'
          name: TraceID
          url: "$${__value.raw}"
